export const projectHeader = [
  {
    SheetTitle: "PROJECT INPUT SHEET: HBS SOLUTION",
    Date: "04-03-2026",
    ProjectUtility: "Washington Gas",
    ProjectName: "Ohr Kodesh Congregation",
    ProjectType: "Small",
    ProgramType: "Building Tune-up",
    SquareFootage: 46370,
    AnnualThermUsage: 14200,
  },
];

export const ecmRows = [
  {
    EnergyConservationMethod: "Optimize HVAC Scheduling",
    EstimatedCost: 10500,
    NaturalGasSavingsThermYr: null,
    CostSavingsYr: null,
    SimplePaybackYears: null,
  },
  {
    EnergyConservationMethod: "AHU temperature scale adjustment",
    EstimatedCost: 5500,
    NaturalGasSavingsThermYr: null,
    CostSavingsYr: null,
    SimplePaybackYears: null,
  },
];

export const ecmSummaryRows = [];

export const hvacRows = [
  {
    Unit: "AHU #1",
    CoolingTonnage: 39.1,
    EERExisting: 10.58584,
    EERProposed: 11.3,
    CoolingEffKWPerTon: null,
    HeatOutputMBH: 469.2,
    HeatingEfficiency: "85%",
    SupplyFanHP: 20,
    SupplyFanUnit: 1,
    SupplyFanMotorLoadFactor: 0.65,
    SupplyFanMotorEfficiency: 0.88,
    SupplyFanMaxCFM: 15640,
    SupplyFanMinCFM: 3910,
    ExhaustFansHP: null,
    ExhaustFanMotorEfficiency: 0.9,
    NumberOfExhaustFans: null,
    ElectricHeating: "No",
  },
  {
    Unit: "AHU #2",
    CoolingTonnage: 61.6,
    EERExisting: 10.58584,
    EERProposed: 11.3,
    CoolingEffKWPerTon: null,
    HeatOutputMBH: 739.2,
    HeatingEfficiency: "85%",
    SupplyFanHP: 20,
    SupplyFanUnit: 1,
    SupplyFanMotorLoadFactor: 0.65,
    SupplyFanMotorEfficiency: 0.88,
    SupplyFanMaxCFM: 24640,
    SupplyFanMinCFM: 6160,
    ExhaustFansHP: null,
    ExhaustFanMotorEfficiency: 0.9,
    NumberOfExhaustFans: null,
    ElectricHeating: "No",
  },
  {
    Unit: "RTU #1",
    CoolingTonnage: 15,
    EERExisting: 9.368,
    EERProposed: 10,
    CoolingEffKWPerTon: null,
    HeatOutputMBH: 180,
    HeatingEfficiency: "85%",
    SupplyFanHP: 1.5,
    SupplyFanUnit: 1,
    SupplyFanMotorLoadFactor: 0.65,
    SupplyFanMotorEfficiency: 0.88,
    SupplyFanMaxCFM: 6000,
    SupplyFanMinCFM: 1500,
    ExhaustFansHP: 6.9,
    ExhaustFanMotorEfficiency: 0.9,
    NumberOfExhaustFans: 1,
    ElectricHeating: "No",
  },
];

export const chillerRows = [
  {
    Unit: "CH 1",
    CoolingTonnage: 100,
    EERExisting: 10.11744,
    EERProposed: 10.8,
    CoolingEffKWPerTon: 1.11,
  },
  {
    Unit: "CH 2",
    CoolingTonnage: 100,
    EERExisting: 10.11744,
    EERProposed: 10.8,
    CoolingEffKWPerTon: 1.11,
  },
];

export const freezerRows = [
  {
    Unit: "Walk-in 1",
    MBH: 6.5,
    EERProposed: 10,
    CoolingEffKWPerTon: 1.2,
    FanMotorHP: 0.066666667,
    FanMotorKW: 0.05,
  },
  {
    Unit: "Walk-in 2",
    MBH: 6.5,
    EERProposed: 10,
    CoolingEffKWPerTon: 1.2,
    FanMotorHP: 0.066666667,
    FanMotorKW: 0.05,
  },
];

export const ecm1DetailOverviewRows = [
  {
    ECM: "ECM-1",
    Description: "Optimize HVAC Scheduling",
    "Estimated Cost ($)": 10500,
    "Natural Gas Savings (Therm/yr)": 6134.32,
    "Electric Savings (kWh/yr)": 174732,
    "Cost Savings ($/yr)": 28942.46,
    "Simple Payback (years)": 0.36,
  },
];

export const ecm1EquipmentRows = [
  {
    Unit: "AHU #1",
    "Cooling Tonnage": 39.1,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 469.2,
    "Supply Fan HP": 20,
    "Supply Fan Max CFM": 15640,
    "Supply Fan Min CFM": 3910,
  },
  {
    Unit: "AHU #2",
    "Cooling Tonnage": 61.6,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 739.2,
    "Supply Fan HP": 20,
    "Supply Fan Max CFM": 24640,
    "Supply Fan Min CFM": 6160,
  },
  {
    Unit: "AHU #3",
    "Cooling Tonnage": 66.5,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 798,
    "Supply Fan HP": 20,
    "Supply Fan Max CFM": 26600,
    "Supply Fan Min CFM": 6650,
  },
  {
    Unit: "AHU #4",
    "Cooling Tonnage": 17.6,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 211.2,
    "Supply Fan HP": 5,
    "Supply Fan Max CFM": 7040,
    "Supply Fan Min CFM": 1760,
  },
  {
    Unit: "AHU #5",
    "Cooling Tonnage": 2.6,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 31.2,
    "Supply Fan HP": 0.75,
    "Supply Fan Max CFM": 1040,
    "Supply Fan Min CFM": 260,
  },
  {
    Unit: "AHU #6",
    "Cooling Tonnage": 7.5,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 90,
    "Supply Fan HP": 5,
    "Supply Fan Max CFM": 3000,
    "Supply Fan Min CFM": 750,
  },
  {
    Unit: "AHU #7",
    "Cooling Tonnage": 3.4,
    "EER (Existing)": 10.58584,
    "EER (Proposed)": 11.3,
    "Heat Output (MBH)": 40.8,
    "Supply Fan HP": 1,
    "Supply Fan Max CFM": 1360,
    "Supply Fan Min CFM": 340,
  },
  {
    Unit: "RTU #1",
    "Cooling Tonnage": 15,
    "EER (Existing)": 9.368,
    "EER (Proposed)": 10,
    "Heat Output (MBH)": 180,
    "Supply Fan HP": 1.5,
    "Supply Fan Max CFM": 6000,
    "Supply Fan Min CFM": 1500,
  },
];

function getEquipmentSortOrder(unitValue: unknown): number {
  const unit = String(unitValue ?? "")
    .trim()
    .toUpperCase();
  const ahuMatch = unit.match(/^AHU\s*#?\s*(\d+)$/);
  if (ahuMatch) {
    return Number(ahuMatch[1]);
  }

  const rtuMatch = unit.match(/^RTU\s*#?\s*(\d+)$/);
  if (rtuMatch) {
    return 100 + Number(rtuMatch[1]);
  }

  return 999;
}

export const ecm1EquipmentRowsOrdered = [...ecm1EquipmentRows].sort(
  (left, right) => {
    const leftOrder = getEquipmentSortOrder(left.Unit);
    const rightOrder = getEquipmentSortOrder(right.Unit);
    if (leftOrder !== rightOrder) return leftOrder - rightOrder;

    return String(left.Unit ?? "").localeCompare(String(right.Unit ?? ""));
  },
);

export const ecm1InputVariables = [
  { "Input Variables": "Cost of Electricity ($/ kwh)", Value: 0.12 },
  { "Input Variables": "Cost of Natural Gas ($/ Therm)", Value: 1.3 },
];

export const ecm1Equations = [
  {
    "Equations & Variables": "Cooling Savings (kWh)",
    Equation: "=Tons*(12/EER)*Bin Hours",
  },
  {
    "Equations & Variables": "Heating Savings (kWh)",
    Equation: "=Heat Capacity*Bin Hours*Load%",
  },
];

export const ecm1AHUEquipmentSummary = [
  {
    "AHU Equipment Values": "Cooling Tonnage",
    "AHU #1": 39.1,
    "AHU #2": 61.6,
    "AHU #3": 66.5,
    "AHU #4": 17.6,
    "AHU #5": 2.6,
    "AHU #6": 7.5,
    "AHU #7": 3.4,
  },
  {
    "AHU Equipment Values": "EER (Proposed)",
    "AHU #1": 11.3,
    "AHU #2": 11.3,
    "AHU #3": 11.3,
    "AHU #4": 11.3,
    "AHU #5": 11.3,
    "AHU #6": 11.3,
    "AHU #7": 11.3,
  },
  {
    "AHU Equipment Values": "Heating Capacity (MBH)",
    "AHU #1": 469.2,
    "AHU #2": 739.2,
    "AHU #3": 798.0,
    "AHU #4": 211.2,
    "AHU #5": 31.2,
    "AHU #6": 90.0,
    "AHU #7": 40.8,
  },
  {
    "AHU Equipment Values": "Heating Efficiency",
    "AHU #1": 0.85,
    "AHU #2": 0.85,
    "AHU #3": 0.85,
    "AHU #4": 0.85,
    "AHU #5": 0.85,
    "AHU #6": 0.85,
    "AHU #7": 0.85,
  },
  {
    "AHU Equipment Values": "Supply Fan HP",
    "AHU #1": 20.0,
    "AHU #2": 20.0,
    "AHU #3": 20.0,
    "AHU #4": 5.0,
    "AHU #5": 0.75,
    "AHU #6": 5.0,
    "AHU #7": 1.0,
  },
  {
    "AHU Equipment Values": "Supply Fan Units",
    "AHU #1": 1.0,
    "AHU #2": 1.0,
    "AHU #3": 1.0,
    "AHU #4": 1.0,
    "AHU #5": 1.0,
    "AHU #6": 1.0,
    "AHU #7": 1.0,
  },
  {
    "AHU Equipment Values": "Electric Heat",
    "AHU #1": "No",
    "AHU #2": "No",
    "AHU #3": "No",
    "AHU #4": "No",
    "AHU #5": "No",
    "AHU #6": "No",
    "AHU #7": "No",
  },
];

export const ecm1EnergyCostSavings = [
  {
    AHU: "AHU #1",
    HeatingSavingsTherms: 3329,
    HeatingCostSavings: 4327.13,
    Spacer: "",
    CoolingSavingsKwh: 28284,
    CoolingCostSavings: 3394.08,
    TotalCostSavings: 7721.21,
  },
  {
    AHU: "AHU #2",
    HeatingSavingsTherms: 0,
    HeatingCostSavings: 0,
    Spacer: "",
    CoolingSavingsKwh: 0,
    CoolingCostSavings: 0,
    TotalCostSavings: 0,
  },
  {
    AHU: "TOTAL",
    HeatingSavingsTherms: 6135,
    HeatingCostSavings: 7974.62,
    Spacer: "",
    CoolingSavingsKwh: 174732,
    CoolingCostSavings: 20967.84,
    TotalCostSavings: 28942.46,
  },
];

export const ecm1TotalSavings = [
  { "Total Savings": "Total Heating Savings (Therms)", Value: 6134.32 },
  { "Total Savings": "Total Cooling Savings (kWh)", Value: 174732 },
  { "Total Savings": "Total Cost Savings ($)", Value: 28942.46 },
];

const binDataKeys = {
  temp: "Temp Mid-Point",
  binExisting: "Bin Hours Existing",
  binProposed: "Bin Hours Proposed",
  eflh: "Equivalent Full Load Hours (%) at Each Bin",
  coolEx: "Existing Cooling kWh",
  coolProp: "Proposed Cooling kWh",
  heatEx: "Existing Heating (Therms)",
  heatProp: "Proposed Heating (Therms)",
  heatSaved: "Heating Therms Saved",
  coolSaved: "Cooling kWh Saved",
};

export const ecm1BinDataAHU1 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 3,
    [binDataKeys.binProposed]: 3,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 125,
    [binDataKeys.coolProp]: 125,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 28,
    [binDataKeys.binProposed]: 26,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 1163,
    [binDataKeys.coolProp]: 1080,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 83,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 72,
    [binDataKeys.binProposed]: 67,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 2638,
    [binDataKeys.coolProp]: 2455,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 183,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 192,
    [binDataKeys.binProposed]: 172,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 6096,
    [binDataKeys.coolProp]: 5461,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 635,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 420,
    [binDataKeys.binProposed]: 354,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 11284,
    [binDataKeys.coolProp]: 9511,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 1773,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 649,
    [binDataKeys.binProposed]: 419,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 14267,
    [binDataKeys.coolProp]: 9211,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 5056,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 819,
    [binDataKeys.binProposed]: 303,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 14003,
    [binDataKeys.coolProp]: 5180,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 8822,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 873,
    [binDataKeys.binProposed]: 292,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 10661,
    [binDataKeys.coolProp]: 3566,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 7095,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 782,
    [binDataKeys.binProposed]: 301,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 5730,
    [binDataKeys.coolProp]: 2206,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 3524,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 768,
    [binDataKeys.binProposed]: 313,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 1876,
    [binDataKeys.coolProp]: 764,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 1111,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 795,
    [binDataKeys.binProposed]: 300,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 146,
    [binDataKeys.heatProp]: 55,
    [binDataKeys.heatSaved]: 91.1,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 551,
    [binDataKeys.binProposed]: 210,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 304,
    [binDataKeys.heatProp]: 116,
    [binDataKeys.heatSaved]: 188.2,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 858,
    [binDataKeys.binProposed]: 290,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 789,
    [binDataKeys.heatProp]: 267,
    [binDataKeys.heatSaved]: 522.6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 651,
    [binDataKeys.binProposed]: 195,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 838,
    [binDataKeys.heatProp]: 251,
    [binDataKeys.heatSaved]: 587.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 476,
    [binDataKeys.binProposed]: 164,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 788,
    [binDataKeys.heatProp]: 272,
    [binDataKeys.heatSaved]: 516.7,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 283,
    [binDataKeys.binProposed]: 80,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 573,
    [binDataKeys.heatProp]: 162,
    [binDataKeys.heatSaved]: 410.9,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 277,
    [binDataKeys.binProposed]: 95,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 663,
    [binDataKeys.heatProp]: 227,
    [binDataKeys.heatSaved]: 435.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 178,
    [binDataKeys.binProposed]: 52,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 491,
    [binDataKeys.heatProp]: 144,
    [binDataKeys.heatSaved]: 347.8,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 71,
    [binDataKeys.binProposed]: 13,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 222,
    [binDataKeys.heatProp]: 41,
    [binDataKeys.heatSaved]: 181.4,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 9,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 31,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 31.5,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 4,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 15,
    [binDataKeys.heatProp]: 4,
    [binDataKeys.heatSaved]: 11.6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 1,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 4,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 4.2,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 8760,
    [binDataKeys.binProposed]: 3650,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 3329,
    [binDataKeys.coolSaved]: 28284,
  },
];

export const ecm1BinDataAHU2 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 2,
    [binDataKeys.binProposed]: 2,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 131,
    [binDataKeys.coolProp]: 131,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 2,
    [binDataKeys.binProposed]: 2,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 131,
    [binDataKeys.coolProp]: 131,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 6,
    [binDataKeys.binProposed]: 6,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 346,
    [binDataKeys.coolProp]: 346,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 20,
    [binDataKeys.binProposed]: 20,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 1000,
    [binDataKeys.coolProp]: 1000,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 37,
    [binDataKeys.binProposed]: 37,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 1566,
    [binDataKeys.coolProp]: 1566,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 20,
    [binDataKeys.binProposed]: 20,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 693,
    [binDataKeys.coolProp]: 693,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 23,
    [binDataKeys.binProposed]: 23,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 620,
    [binDataKeys.coolProp]: 620,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 14,
    [binDataKeys.binProposed]: 14,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 269,
    [binDataKeys.coolProp]: 269,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 15,
    [binDataKeys.binProposed]: 15,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 173,
    [binDataKeys.coolProp]: 173,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 30,
    [binDataKeys.binProposed]: 30,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 115,
    [binDataKeys.coolProp]: 115,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 21,
    [binDataKeys.binProposed]: 21,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 6,
    [binDataKeys.heatProp]: 6,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 24,
    [binDataKeys.binProposed]: 24,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 21,
    [binDataKeys.heatProp]: 21,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 11,
    [binDataKeys.binProposed]: 11,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 16,
    [binDataKeys.heatProp]: 16,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 11,
    [binDataKeys.binProposed]: 11,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 22,
    [binDataKeys.heatProp]: 22,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 3,
    [binDataKeys.binProposed]: 3,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 8,
    [binDataKeys.heatProp]: 8,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 10,
    [binDataKeys.binProposed]: 10,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 32,
    [binDataKeys.heatProp]: 32,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 6,
    [binDataKeys.binProposed]: 6,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 23,
    [binDataKeys.heatProp]: 23,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 5,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 22,
    [binDataKeys.heatProp]: 22,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 260,
    [binDataKeys.binProposed]: 260,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: 0,
  },
];

export const ecm1BinDataAHU3 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 353,
    [binDataKeys.coolProp]: 0,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 353,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 40,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 2825,
    [binDataKeys.coolProp]: 0,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 2825,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 229,
    [binDataKeys.binProposed]: 2,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 14269,
    [binDataKeys.coolProp]: 125,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 14145,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 435,
    [binDataKeys.binProposed]: 11,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 23491,
    [binDataKeys.coolProp]: 594,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 22897,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 713,
    [binDataKeys.binProposed]: 77,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 32580,
    [binDataKeys.coolProp]: 3519,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 29062,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 775,
    [binDataKeys.binProposed]: 187,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 28975,
    [binDataKeys.coolProp]: 6991,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 21983,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 1091,
    [binDataKeys.binProposed]: 211,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 31725,
    [binDataKeys.coolProp]: 6136,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 25589,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 1039,
    [binDataKeys.binProposed]: 203,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 21580,
    [binDataKeys.coolProp]: 4216,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 17364,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 894,
    [binDataKeys.binProposed]: 158,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 11141,
    [binDataKeys.coolProp]: 1969,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 9172,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 759,
    [binDataKeys.binProposed]: 153,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 3153,
    [binDataKeys.coolProp]: 636,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 2517,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 640,
    [binDataKeys.binProposed]: 145,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 200,
    [binDataKeys.heatProp]: 45,
    [binDataKeys.heatSaved]: 154.9,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 671,
    [binDataKeys.binProposed]: 206,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 630,
    [binDataKeys.heatProp]: 193,
    [binDataKeys.heatSaved]: 436.6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 673,
    [binDataKeys.binProposed]: 162,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 1053,
    [binDataKeys.heatProp]: 253,
    [binDataKeys.heatSaved]: 799.6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 287,
    [binDataKeys.binProposed]: 103,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 629,
    [binDataKeys.heatProp]: 226,
    [binDataKeys.heatSaved]: 403.1,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 196,
    [binDataKeys.binProposed]: 79,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 552,
    [binDataKeys.heatProp]: 223,
    [binDataKeys.heatSaved]: 329.5,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 214,
    [binDataKeys.binProposed]: 65,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 737,
    [binDataKeys.heatProp]: 224,
    [binDataKeys.heatSaved]: 512.9,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 83,
    [binDataKeys.binProposed]: 39,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 338,
    [binDataKeys.heatProp]: 159,
    [binDataKeys.heatSaved]: 179.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 10,
    [binDataKeys.binProposed]: 23,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 47,
    [binDataKeys.heatProp]: 108,
    [binDataKeys.heatSaved]: -61.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 27,
    [binDataKeys.heatProp]: 5,
    [binDataKeys.heatSaved]: 21.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 1,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 6,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 5.9,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 8760,
    [binDataKeys.binProposed]: 1825,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 2782,
    [binDataKeys.coolSaved]: 145908,
  },
];

export const ecm1BinDataAHU4 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 5,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 93,
    [binDataKeys.coolProp]: 93,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 40,
    [binDataKeys.binProposed]: 40,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 748,
    [binDataKeys.coolProp]: 748,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 229,
    [binDataKeys.binProposed]: 229,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 3777,
    [binDataKeys.coolProp]: 3777,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 435,
    [binDataKeys.binProposed]: 435,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 6217,
    [binDataKeys.coolProp]: 6217,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 713,
    [binDataKeys.binProposed]: 713,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 8623,
    [binDataKeys.coolProp]: 8623,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 775,
    [binDataKeys.binProposed]: 775,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 7669,
    [binDataKeys.coolProp]: 7669,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 1091,
    [binDataKeys.binProposed]: 1091,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 8396,
    [binDataKeys.coolProp]: 8396,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 1039,
    [binDataKeys.binProposed]: 1039,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 5712,
    [binDataKeys.coolProp]: 5712,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 894,
    [binDataKeys.binProposed]: 894,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 2949,
    [binDataKeys.coolProp]: 2949,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 759,
    [binDataKeys.binProposed]: 759,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 834,
    [binDataKeys.coolProp]: 834,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 640,
    [binDataKeys.binProposed]: 640,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 53,
    [binDataKeys.heatProp]: 53,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 671,
    [binDataKeys.binProposed]: 671,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 167,
    [binDataKeys.heatProp]: 167,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 673,
    [binDataKeys.binProposed]: 673,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 279,
    [binDataKeys.heatProp]: 279,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 287,
    [binDataKeys.binProposed]: 287,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 166,
    [binDataKeys.heatProp]: 166,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 196,
    [binDataKeys.binProposed]: 196,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 146,
    [binDataKeys.heatProp]: 146,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 214,
    [binDataKeys.binProposed]: 214,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 195,
    [binDataKeys.heatProp]: 195,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 83,
    [binDataKeys.binProposed]: 83,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 89,
    [binDataKeys.heatProp]: 89,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 10,
    [binDataKeys.binProposed]: 10,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 12,
    [binDataKeys.heatProp]: 12,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 5,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 7,
    [binDataKeys.heatProp]: 7,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 1,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 2,
    [binDataKeys.heatProp]: 2,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 8760,
    [binDataKeys.binProposed]: 8760,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: 0,
  },
];

export const ecm1BinDataAHU5 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 3,
    [binDataKeys.binProposed]: 3,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 8,
    [binDataKeys.coolProp]: 8,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 28,
    [binDataKeys.binProposed]: 26,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 77,
    [binDataKeys.coolProp]: 72,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 70,
    [binDataKeys.binProposed]: 67,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 171,
    [binDataKeys.coolProp]: 163,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 7,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 184,
    [binDataKeys.binProposed]: 172,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 388,
    [binDataKeys.coolProp]: 363,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 25,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 384,
    [binDataKeys.binProposed]: 356,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 686,
    [binDataKeys.coolProp]: 636,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 50,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 476,
    [binDataKeys.binProposed]: 440,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 696,
    [binDataKeys.coolProp]: 643,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 53,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 385,
    [binDataKeys.binProposed]: 344,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 438,
    [binDataKeys.coolProp]: 391,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 47,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 364,
    [binDataKeys.binProposed]: 325,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 296,
    [binDataKeys.coolProp]: 264,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 32,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 354,
    [binDataKeys.binProposed]: 334,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 172,
    [binDataKeys.coolProp]: 163,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 10,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 379,
    [binDataKeys.binProposed]: 346,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 62,
    [binDataKeys.coolProp]: 56,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 5,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 369,
    [binDataKeys.binProposed]: 337,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 5,
    [binDataKeys.heatProp]: 4,
    [binDataKeys.heatSaved]: 0.4,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 255,
    [binDataKeys.binProposed]: 229,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 9,
    [binDataKeys.heatProp]: 8,
    [binDataKeys.heatSaved]: 1.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 357,
    [binDataKeys.binProposed]: 328,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 22,
    [binDataKeys.heatProp]: 20,
    [binDataKeys.heatSaved]: 1.8,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 245,
    [binDataKeys.binProposed]: 227,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 21,
    [binDataKeys.heatProp]: 19,
    [binDataKeys.heatSaved]: 1.5,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 214,
    [binDataKeys.binProposed]: 193,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 24,
    [binDataKeys.heatProp]: 21,
    [binDataKeys.heatSaved]: 2.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 101,
    [binDataKeys.binProposed]: 93,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 14,
    [binDataKeys.heatProp]: 13,
    [binDataKeys.heatSaved]: 1.1,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 118,
    [binDataKeys.binProposed]: 108,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 19,
    [binDataKeys.heatProp]: 17,
    [binDataKeys.heatSaved]: 1.6,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 71,
    [binDataKeys.binProposed]: 65,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 13,
    [binDataKeys.heatProp]: 12,
    [binDataKeys.heatSaved]: 1.1,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 19,
    [binDataKeys.binProposed]: 18,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 4,
    [binDataKeys.heatProp]: 4,
    [binDataKeys.heatSaved]: 0.2,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 2,
    [binDataKeys.binProposed]: 2,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: -0.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: -0.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 4378,
    [binDataKeys.binProposed]: 4015,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 10,
    [binDataKeys.coolSaved]: 234,
  },
];

export const ecm1BinDataAHU6 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 3,
    [binDataKeys.binProposed]: 3,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 24,
    [binDataKeys.coolProp]: 24,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 5,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 40,
    [binDataKeys.coolProp]: 40,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 20,
    [binDataKeys.binProposed]: 20,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 141,
    [binDataKeys.coolProp]: 141,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 39,
    [binDataKeys.binProposed]: 39,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 238,
    [binDataKeys.coolProp]: 238,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 48,
    [binDataKeys.binProposed]: 48,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 247,
    [binDataKeys.coolProp]: 247,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 41,
    [binDataKeys.binProposed]: 41,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 173,
    [binDataKeys.coolProp]: 173,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 30,
    [binDataKeys.binProposed]: 30,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 98,
    [binDataKeys.coolProp]: 98,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 21,
    [binDataKeys.binProposed]: 21,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 49,
    [binDataKeys.coolProp]: 49,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 39,
    [binDataKeys.binProposed]: 39,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 55,
    [binDataKeys.coolProp]: 55,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 42,
    [binDataKeys.binProposed]: 42,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 3,
    [binDataKeys.heatProp]: 3,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: 0,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 23,
    [binDataKeys.binProposed]: 23,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 1,
    [binDataKeys.heatProp]: 1,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 37,
    [binDataKeys.binProposed]: 37,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 4,
    [binDataKeys.heatProp]: 4,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 18,
    [binDataKeys.binProposed]: 18,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 3,
    [binDataKeys.heatProp]: 3,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 14,
    [binDataKeys.binProposed]: 14,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 3,
    [binDataKeys.heatProp]: 3,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 6,
    [binDataKeys.binProposed]: 6,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 2,
    [binDataKeys.heatProp]: 2,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 16,
    [binDataKeys.binProposed]: 16,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 6,
    [binDataKeys.heatProp]: 6,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 9,
    [binDataKeys.binProposed]: 9,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 4,
    [binDataKeys.heatProp]: 4,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 5,
    [binDataKeys.binProposed]: 5,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 3,
    [binDataKeys.heatProp]: 3,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 0,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 416,
    [binDataKeys.binProposed]: 416,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: 0,
  },
];

export const ecm1BinDataAHU7 = [
  {
    [binDataKeys.temp]: 102.5,
    [binDataKeys.binExisting]: 3,
    [binDataKeys.binProposed]: 3,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 11,
    [binDataKeys.coolProp]: 11,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 97.5,
    [binDataKeys.binExisting]: 28,
    [binDataKeys.binProposed]: 26,
    [binDataKeys.eflh]: "100.00%",
    [binDataKeys.coolEx]: 101,
    [binDataKeys.coolProp]: 94,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 7,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 92.5,
    [binDataKeys.binExisting]: 70,
    [binDataKeys.binProposed]: 67,
    [binDataKeys.eflh]: "88.24%",
    [binDataKeys.coolEx]: 223,
    [binDataKeys.coolProp]: 213,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 10,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 87.5,
    [binDataKeys.binExisting]: 184,
    [binDataKeys.binProposed]: 172,
    [binDataKeys.eflh]: "76.47%",
    [binDataKeys.coolEx]: 508,
    [binDataKeys.coolProp]: 475,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 33,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 82.5,
    [binDataKeys.binExisting]: 384,
    [binDataKeys.binProposed]: 356,
    [binDataKeys.eflh]: "64.71%",
    [binDataKeys.coolEx]: 897,
    [binDataKeys.coolProp]: 832,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 65,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 77.5,
    [binDataKeys.binExisting]: 476,
    [binDataKeys.binProposed]: 440,
    [binDataKeys.eflh]: "52.94%",
    [binDataKeys.coolEx]: 910,
    [binDataKeys.coolProp]: 841,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 69,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 72.5,
    [binDataKeys.binExisting]: 385,
    [binDataKeys.binProposed]: 344,
    [binDataKeys.eflh]: "41.18%",
    [binDataKeys.coolEx]: 572,
    [binDataKeys.coolProp]: 511,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 61,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 67.5,
    [binDataKeys.binExisting]: 364,
    [binDataKeys.binProposed]: 325,
    [binDataKeys.eflh]: "29.41%",
    [binDataKeys.coolEx]: 387,
    [binDataKeys.coolProp]: 345,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 41,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 62.5,
    [binDataKeys.binExisting]: 354,
    [binDataKeys.binProposed]: 334,
    [binDataKeys.eflh]: "17.65%",
    [binDataKeys.coolEx]: 226,
    [binDataKeys.coolProp]: 213,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 13,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 57.5,
    [binDataKeys.binExisting]: 379,
    [binDataKeys.binProposed]: 346,
    [binDataKeys.eflh]: "5.88%",
    [binDataKeys.coolEx]: 80,
    [binDataKeys.coolProp]: 73,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 7,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 52.5,
    [binDataKeys.binExisting]: 369,
    [binDataKeys.binProposed]: 337,
    [binDataKeys.eflh]: "3.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 6,
    [binDataKeys.heatProp]: 5,
    [binDataKeys.heatSaved]: 0.5,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 47.5,
    [binDataKeys.binExisting]: 255,
    [binDataKeys.binProposed]: 229,
    [binDataKeys.eflh]: "10.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 12,
    [binDataKeys.heatProp]: 11,
    [binDataKeys.heatSaved]: 1.2,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 42.5,
    [binDataKeys.binExisting]: 357,
    [binDataKeys.binProposed]: 328,
    [binDataKeys.eflh]: "16.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 29,
    [binDataKeys.heatProp]: 26,
    [binDataKeys.heatSaved]: 2.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 37.5,
    [binDataKeys.binExisting]: 245,
    [binDataKeys.binProposed]: 227,
    [binDataKeys.eflh]: "23.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 27,
    [binDataKeys.heatProp]: 25,
    [binDataKeys.heatSaved]: 2.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 32.5,
    [binDataKeys.binExisting]: 214,
    [binDataKeys.binProposed]: 193,
    [binDataKeys.eflh]: "30.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 31,
    [binDataKeys.heatProp]: 28,
    [binDataKeys.heatSaved]: 3.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 27.5,
    [binDataKeys.binExisting]: 101,
    [binDataKeys.binProposed]: 93,
    [binDataKeys.eflh]: "36.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 18,
    [binDataKeys.heatProp]: 16,
    [binDataKeys.heatSaved]: 1.4,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 22.5,
    [binDataKeys.binExisting]: 118,
    [binDataKeys.binProposed]: 108,
    [binDataKeys.eflh]: "43.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 25,
    [binDataKeys.heatProp]: 22,
    [binDataKeys.heatSaved]: 2.1,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 17.5,
    [binDataKeys.binExisting]: 71,
    [binDataKeys.binProposed]: 65,
    [binDataKeys.eflh]: "50.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 17,
    [binDataKeys.heatProp]: 16,
    [binDataKeys.heatSaved]: 1.4,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 12.5,
    [binDataKeys.binExisting]: 19,
    [binDataKeys.binProposed]: 18,
    [binDataKeys.eflh]: "56.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 5,
    [binDataKeys.heatProp]: 5,
    [binDataKeys.heatSaved]: 0.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 7.5,
    [binDataKeys.binExisting]: 2,
    [binDataKeys.binProposed]: 2,
    [binDataKeys.eflh]: "63.33%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 1,
    [binDataKeys.heatProp]: 1,
    [binDataKeys.heatSaved]: 0.0,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: 2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "70.00%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: -0.3,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: -2.5,
    [binDataKeys.binExisting]: 0,
    [binDataKeys.binProposed]: 1,
    [binDataKeys.eflh]: "76.67%",
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: 0,
    [binDataKeys.heatProp]: 0,
    [binDataKeys.heatSaved]: -0.4,
    [binDataKeys.coolSaved]: null,
  },
  {
    [binDataKeys.temp]: "Totals",
    [binDataKeys.binExisting]: 4378,
    [binDataKeys.binProposed]: 4015,
    [binDataKeys.eflh]: null,
    [binDataKeys.coolEx]: null,
    [binDataKeys.coolProp]: null,
    [binDataKeys.heatEx]: null,
    [binDataKeys.heatProp]: null,
    [binDataKeys.heatSaved]: 14,
    [binDataKeys.coolSaved]: 306,
  },
];

export const ECM1_DETAIL_SHEET_NAME = "ECM1";
